name: Post Comment
on:
  workflow_dispatch:
  schedule: [{ cron: 30 1-23/3 * * * }]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.JS
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3.3.2
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Post Comment
        run: pnpm run comment
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
