name: Download and Install WinGet Dependencies

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download WinGet and its dependencies
      shell: pwsh
      run: |
        Install-Module -Name powershell-yaml -Force -Scope CurrentUser -Repository PSGallery
        Install-Module -Name Microsoft.WinGet.Client -Force -Scope CurrentUser -Repository PSGallery
        Repair-WinGetPackageManager -Latest -AllUsers -Verbose
        winget settings --enable LocalManifestFiles
        winget --info
        winget install wingetcreate --accept-source-agreements --accept-package-agreements
        wingetcreate
        $settingsFilePath = Get-ChildItem -Path $env:USERPROFILE -Recurse -Filter "settings.json" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName
        if ($settingsFilePath) {
          Write-Output "Le fichier settings.json a été trouvé à l'emplacement : $settingsFilePath"
        } else {
          Write-Output "Le fichier settings.json n'a pas été trouvé."
        }