name: Auto Remove
on:
  workflow_dispatch:
  schedule: [{ cron: 0 12 * * 4 }]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: |
          python3 -m pip install -r requirements.txt
          git clone https://github.com/microsoft/winget-pkgs
      - name: Run script
        run: python3 src/scanner.py ${{ secrets.TOKEN }}
