name: Auto Remove
on:
  workflow_dispatch:
  schedule: [{ cron: 0 0 * * * }]

jobs:
  Remove:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdirectory: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Rust
        # 用于后续的 `cargo binstall` 安装
        uses: cargo-bins/cargo-binstall@main
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install Komac
        run: cargo binstall komac -y
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          git clone https://github.com/microsoft/winget-pkgs
          pnpm install

      - name: Scan
        run: python3 src/scanner.py ${{ matrix.subdirectory }}
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Post Issue
        run: pnpm run issue
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
