name: Close Stale Issue and PR
on:
  schedule: [{ cron: 30 * * * * }]
  workflow_dispatch:
jobs:
  stale:
    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
          exempt-issue-labels: "WIP,NeverExpires,Blocking-issue"
          exempt-pr-labels: "NeverExpires,Blocking-issue"
          stale-issue-label: "stale"
